var express = require("express");
var router = express.Router();
const staticListOfBonds = [
  {
    BondID: "GB001",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2029-08-13",
    CouponRate: 1.5,
    FaceValue: 5000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 1,
  },
  {
    BondID: "GB002",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2028-06-15",
    CouponRate: 2.0,
    FaceValue: 10000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 2,
  },
  {
    BondID: "GB003",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2030-11-30",
    CouponRate: 1.75,
    FaceValue: 20000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 3,
  },
  {
    BondID: "GB004",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2027-05-01",
    CouponRate: 1.25,
    FaceValue: 15000,
    FaceValue: 16000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 4,
  },
  {
    BondID: "GB005",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2031-09-12",
    CouponRate: 1.6,
    FaceValue: 1000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 5,
  },
  {
    BondID: "GB006",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2026-07-20",
    CouponRate: 2.5,
    FaceValue: 25000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 6,
  },
  {
    BondID: "GB007",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2029-10-01",
    CouponRate: 1.3,
    FaceValue: 40000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 7,
  },
  {
    BondID: "GB008",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2033-02-25",
    CouponRate: 2.0,
    FaceValue: 50000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 8,
  },
  {
    BondID: "GB009",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2027-03-15",
    CouponRate: 1.8,
    FaceValue: 10000,
    FaceValue: 11000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 9,
  },
  {
    BondID: "GB010",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2034-04-10",
    CouponRate: 1.9,
    FaceValue: 75000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 10,
  },
  {
    BondID: "GB011",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2038-12-01",
    CouponRate: 2.5,
    FaceValue: 30000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 11,
  },
  {
    BondID: "GB012",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2031-08-13",
    CouponRate: 2.0,
    FaceValue: 100000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 12,
  },
  {
    BondID: "GB013",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2029-01-01",
    CouponRate: 1.5,
    FaceValue: 15000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 13,
  },
  {
    BondID: "GB014",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2032-09-30",
    CouponRate: 1.7,
    FaceValue: 12000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 14,
  },
  {
    BondID: "GB015",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2026-02-15",
    CouponRate: 1.6,
    FaceValue: 45000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 15,
  },
  {
    BondID: "GB016",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2040-10-12",
    CouponRate: 3.0,
    FaceValue: 90000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 16,
  },
  {
    BondID: "GB017",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2035-03-01",
    CouponRate: 2.25,
    FaceValue: 65000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 17,
  },
  {
    BondID: "GB018",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2033-07-07",
    CouponRate: 1.9,
    FaceValue: 3000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 18,
  },
  {
    BondID: "GB019",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2037-08-30",
    CouponRate: 2.8,
    FaceValue: 70000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 19,
  },
  {
    BondID: "GB020",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2029-11-01",
    CouponRate: 1.4,
    FaceValue: 35000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 20,
  },
  {
    BondID: "GB021",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2035-06-15",
    CouponRate: 2.1,
    FaceValue: 40000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 21,
  },
  {
    BondID: "GB022",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2028-04-30",
    CouponRate: 1.8,
    FaceValue: 12000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 22,
  },
  {
    BondID: "GB023",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2031-12-01",
    CouponRate: 2.3,
    FaceValue: 60000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 23,
  },
  {
    BondID: "GB024",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2025-11-15",
    CouponRate: 1.4,
    FaceValue: 15000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 24,
  },
  {
    BondID: "GB025",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2036-09-30",
    CouponRate: 2.7,
    FaceValue: 20000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 25,
  },
  {
    BondID: "GB026",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2028-07-01",
    CouponRate: 2.2,
    FaceValue: 8000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 26,
  },
  {
    BondID: "GB027",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2032-01-15",
    CouponRate: 1.9,
    FaceValue: 30000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 27,
  },
  {
    BondID: "GB028",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2026-09-01",
    CouponRate: 1.6,
    FaceValue: 5000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 28,
  },
  {
    BondID: "GB029",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2037-05-15",
    CouponRate: 2.5,
    FaceValue: 70000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 29,
  },
  {
    BondID: "GB030",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2030-04-01",
    CouponRate: 2.0,
    FaceValue: 15000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 30,
  },
  {
    BondID: "GB031",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2029-12-15",
    CouponRate: 1.7,
    FaceValue: 18000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 31,
  },
  {
    BondID: "GB032",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2038-05-01",
    CouponRate: 2.4,
    FaceValue: 55000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 32,
  },
  {
    BondID: "GB033",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2034-08-15",
    CouponRate: 1.8,
    FaceValue: 25000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 33,
  },
  {
    BondID: "GB034",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2031-07-01",
    CouponRate: 2.2,
    FaceValue: 80000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 34,
  },
  {
    BondID: "GB035",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2025-10-01",
    CouponRate: 1.5,
    FaceValue: 22000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 35,
  },
  {
    BondID: "GB036",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2026-05-01",
    CouponRate: 2.3,
    FaceValue: 35000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 36,
  },
  {
    BondID: "GB037",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2036-12-01",
    CouponRate: 2.6,
    FaceValue: 65000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 37,
  },
  {
    BondID: "GB038",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2028-03-01",
    CouponRate: 2.0,
    FaceValue: 11000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 38,
  },
  {
    BondID: "GB039",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2030-08-15",
    CouponRate: 1.9,
    FaceValue: 7000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 39,
  },
  {
    BondID: "GB040",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2027-09-01",
    CouponRate: 1.6,
    FaceValue: 27000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 40,
  },
  {
    BondID: "GB041",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2032-10-15",
    CouponRate: 2.1,
    FaceValue: 45000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 41,
  },
  {
    BondID: "GB042",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2039-01-01",
    CouponRate: 2.4,
    FaceValue: 50000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 42,
  },
  {
    BondID: "GB043",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2026-11-01",
    CouponRate: 1.8,
    FaceValue: 35000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 43,
  },
  {
    BondID: "GB044",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2027-04-01",
    CouponRate: 2.1,
    FaceValue: 12000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 44,
  },
  {
    BondID: "GB045",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2031-03-15",
    CouponRate: 1.7,
    FaceValue: 35000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 45,
  },
  {
    BondID: "GB046",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2034-07-01",
    CouponRate: 2.2,
    FaceValue: 9000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 46,
  },
  {
    BondID: "GB047",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2029-05-01",
    CouponRate: 2.0,
    FaceValue: 55000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 47,
  },
  {
    BondID: "GB048",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2036-08-15",
    CouponRate: 1.8,
    FaceValue: 14000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 48,
  },
  {
    BondID: "GB049",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2033-11-01",
    CouponRate: 2.5,
    FaceValue: 10000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 49,
  },
  {
    BondID: "GB050",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2026-04-15",
    CouponRate: 1.4,
    FaceValue: 20000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 50,
  },
  {
    BondID: "GB051",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2039-04-01",
    CouponRate: 2.0,
    FaceValue: 70000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 51,
  },
  {
    BondID: "GB052",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2027-12-01",
    CouponRate: 2.3,
    FaceValue: 28000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 52,
  },
  {
    BondID: "GB053",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2032-03-01",
    CouponRate: 1.9,
    FaceValue: 40000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 53,
  },
  {
    BondID: "GB054",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2025-05-15",
    CouponRate: 1.5,
    FaceValue: 8000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 54,
  },
  {
    BondID: "GB055",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2037-10-01",
    CouponRate: 2.2,
    FaceValue: 22000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 55,
  },
  {
    BondID: "GB056",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2031-09-01",
    CouponRate: 1.6,
    FaceValue: 60000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 56,
  },
  {
    BondID: "GB057",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2035-11-01",
    CouponRate: 2.1,
    FaceValue: 40000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 57,
  },
  {
    BondID: "GB058",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2029-07-01",
    CouponRate: 1.8,
    FaceValue: 15000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 58,
  },
  {
    BondID: "GB059",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2028-12-01",
    CouponRate: 2.0,
    FaceValue: 10000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 59,
  },
  {
    BondID: "GB060",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2039-11-01",
    CouponRate: 2.4,
    FaceValue: 80000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 60,
  },
  {
    BondID: "GB061",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2026-08-01",
    CouponRate: 1.7,
    FaceValue: 35000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 61,
  },
  {
    BondID: "GB062",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2034-11-01",
    CouponRate: 2.3,
    FaceValue: 5000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 62,
  },
  {
    BondID: "GB063",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2025-06-01",
    CouponRate: 1.9,
    FaceValue: 20000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 63,
  },
  {
    BondID: "GB064",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2029-08-01",
    CouponRate: 1.6,
    FaceValue: 12000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 64,
  },
  {
    BondID: "GB065",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2033-04-01",
    CouponRate: 2.1,
    FaceValue: 60000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 65,
  },
  {
    BondID: "GB066",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2025-01-01",
    CouponRate: 2.0,
    FaceValue: 30000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 66,
  },
  {
    BondID: "GB067",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2038-09-01",
    CouponRate: 2.6,
    FaceValue: 75000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 67,
  },
  {
    BondID: "GB068",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2027-11-01",
    CouponRate: 1.7,
    FaceValue: 14000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 68,
  },
  {
    BondID: "GB069",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2032-07-01",
    CouponRate: 2.3,
    FaceValue: 25000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 69,
  },
  {
    BondID: "GB070",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2035-02-01",
    CouponRate: 1.8,
    FaceValue: 16000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 70,
  },
  {
    BondID: "GB071",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2037-07-01",
    CouponRate: 2.4,
    FaceValue: 45000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 71,
  },
  {
    BondID: "GB072",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2028-11-01",
    CouponRate: 1.9,
    FaceValue: 50000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 72,
  },
  {
    BondID: "GB073",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2025-09-01",
    CouponRate: 2.2,
    FaceValue: 7000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 73,
  },
  {
    BondID: "GB074",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2038-01-01",
    CouponRate: 2.5,
    FaceValue: 60000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 74,
  },
  {
    BondID: "GB075",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2026-06-01",
    CouponRate: 1.4,
    FaceValue: 30000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 75,
  },
  {
    BondID: "GB076",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2030-10-01",
    CouponRate: 2.0,
    FaceValue: 25000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 76,
  },
  {
    BondID: "GB077",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2033-03-01",
    CouponRate: 1.8,
    FaceValue: 32000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 77,
  },
  {
    BondID: "GB078",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2025-12-01",
    CouponRate: 2.1,
    FaceValue: 15000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 78,
  },
  {
    BondID: "GB079",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2032-06-01",
    CouponRate: 2.3,
    FaceValue: 9000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 79,
  },
  {
    BondID: "GB080",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2027-10-01",
    CouponRate: 2.2,
    FaceValue: 25000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 80,
  },
  {
    BondID: "GB081",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2029-06-01",
    CouponRate: 1.6,
    FaceValue: 17000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 81,
  },
  {
    BondID: "GB082",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2035-07-01",
    CouponRate: 2.0,
    FaceValue: 28000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 82,
  },
  {
    BondID: "GB083",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2026-03-01",
    CouponRate: 1.9,
    FaceValue: 15000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 83,
  },
  {
    BondID: "GB084",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2033-12-01",
    CouponRate: 2.1,
    FaceValue: 70000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 84,
  },
  {
    BondID: "GB085",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2028-01-01",
    CouponRate: 2.2,
    FaceValue: 20000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 85,
  },
  {
    BondID: "GB086",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2031-11-01",
    CouponRate: 1.8,
    FaceValue: 30000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 86,
  },
  {
    BondID: "GB087",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2027-07-01",
    CouponRate: 1.5,
    FaceValue: 18000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 87,
  },
  {
    BondID: "GB088",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2034-01-01",
    CouponRate: 2.0,
    FaceValue: 60000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 88,
  },
  {
    BondID: "GB089",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2039-05-01",
    CouponRate: 2.4,
    FaceValue: 50000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 89,
  },
  {
    BondID: "GB090",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2036-06-01",
    CouponRate: 1.7,
    FaceValue: 12000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 90,
  },
  {
    BondID: "GB091",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2025-10-01",
    CouponRate: 1.8,
    FaceValue: 25000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 91,
  },
  {
    BondID: "GB092",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2039-08-01",
    CouponRate: 2.5,
    FaceValue: 55000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 92,
  },
  {
    BondID: "GB093",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2030-02-01",
    CouponRate: 2.2,
    FaceValue: 30000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 93,
  },
  {
    BondID: "GB094",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2037-01-01",
    CouponRate: 2.1,
    FaceValue: 70000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 94,
  },
  {
    BondID: "GB095",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2034-06-01",
    CouponRate: 1.9,
    FaceValue: 25000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 95,
  },
  {
    BondID: "GB096",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2031-07-01",
    CouponRate: 2.0,
    FaceValue: 40000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 96,
  },
  {
    BondID: "GB097",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2025-07-01",
    CouponRate: 2.3,
    FaceValue: 50000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 97,
  },
  {
    BondID: "GB098",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2027-08-01",
    CouponRate: 1.8,
    FaceValue: 16000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 98,
  },
  {
    BondID: "GB099",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2039-02-01",
    CouponRate: 2.4,
    FaceValue: 90000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 99,
  },
  {
    BondID: "GB100",
    Issuer: "British Government",
    Symbol: "UKGILT5Y",
    MaturityDate: "2037-03-01",
    CouponRate: 2.1,
    FaceValue: 45000,
    Currency: "GBP",
    purchased: false,
    burnt: false,
    owner: "",
    bondNId: 100,
  },
];

process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0;

var getListOfVirtualNodes = require("./services/common/getListOfVirtualNodes");
var issueTokenOnLedger = require("./services/buy/issueTokenOnLedger");
var getListOfGovernmentBondsForUser = require("./services/list/getListOfGovernmentBondsForUser");
var burnTokenOnLedger = require("./services/burn/burnTokenOnLedger");
var submitMessage = require("./services/hadera/haderaConsensus");

router.get("/", function (req, res, next) {
  const listOfAvailableBonds = staticListOfBonds.filter((bond) => {
    return !bond.purchased;
  });

  res.json(listOfAvailableBonds);
});

router.post("/buy", async function (req, res, next) {
  const { buyerName, bondId } = req.body;

  const foundBondIndex = staticListOfBonds.findIndex((bond) => {
    return bond.BondID === bondId;
  });

  if (foundBondIndex === -1) {
    res.status(400).json({
      status: 400,
      message: "Unkown Bond ID",
    });
  } else if (staticListOfBonds[foundBondIndex].purchased) {
    res.status(400).json({
      status: 400,
      message: "Bond has already been purchased",
    });
  }

  staticListOfBonds[foundBondIndex].purchased = true;
  staticListOfBonds[foundBondIndex].owner = buyerName;

  const { governmentHoldingIdentity, buyerHoldingIdentity } =
    await getListOfVirtualNodes(buyerName);

  const issueTokenResponse = await issueTokenOnLedger(
    governmentHoldingIdentity,
    buyerHoldingIdentity,
    staticListOfBonds[foundBondIndex]
  );

  await new Promise((resolve) => setTimeout(resolve, 1500));

  res.json({ issueTokenResponse });
});

router.get("/list", async function (req, res, next) {
  const { name } = req.query;

  const { buyerHoldingIdentity } = await getListOfVirtualNodes(name);

  const result = await getListOfGovernmentBondsForUser(
    buyerHoldingIdentity.shortHash
  );

  const listOfOwnedGovernmentBondsOnPrivateLedgerUnformated = result;

  const listOfGovernmentBondsOnPublicLedgerUnformated =
    staticListOfBonds.filter((bond) => {
      return bond.purchased && bond.burnt && bond.owner === name;
    });

  const listOfGovernmentBondsOnPublicLedger =
    listOfGovernmentBondsOnPublicLedgerUnformated.map((publicBonds) => {
      return {
        issuer: "",
        symbol: publicBonds.Symbol,
        value: publicBonds.FaceValue,
        owner: publicBonds.owner,
        issuerCommonName: publicBonds.Issuer,
        ownerCommonName: publicBonds.owner,
        bondId: publicBonds.BondID,
        maturityDate: publicBonds.MaturityDate,
        couponRate: publicBonds.CouponRate,
        currency: "GBP",
        public: true,
      };
    });

  const listOfGovernmentBondsOnPrivateLedger =
    listOfOwnedGovernmentBondsOnPrivateLedgerUnformated.map((bond) => {
      return {
        ...bond,
        public: false,
      };
    });

  res.json([
    ...listOfGovernmentBondsOnPrivateLedger,
    ...listOfGovernmentBondsOnPublicLedger,
  ]);
});

router.post("/burn", async function (req, res, next) {
  const { ownerName, bondId } = req.body;

  const { buyerHoldingIdentity } = await getListOfVirtualNodes(ownerName);

  // Find the bond...
  const foundBondIndex = staticListOfBonds.findIndex((bond) => {
    return bond.BondID === bondId;
  });

  const bond = staticListOfBonds[foundBondIndex];

  if (foundBondIndex === -1) {
    res.status(400).json({
      status: 400,
      message: "Unkown Bond ID",
    });
    return;
  } else if (bond.purchased === false) {
    res.status(400).json({
      status: 400,
      message: "Bond has not been purchased",
    });
    return;
  }

  await burnTokenOnLedger(buyerHoldingIdentity, bond);

  bond.burnt = true;

  submitMessage(bond);

  res.status(200).json({
    message: "Burnt token",
  });
});

module.exports = router;
